### ISSUE TITLE
Unregister "colors" panel in customizer

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/allegiant-lite#10]
Asta trebuie sa dispara.

**Comment by giucu91** [comment]
@cristianraiber si background color il bag la background Image ?

**Comment by cristianraiber** [comment]
@giucu91 - dap

**Comment by giucu91** [comment]
@cristianraiber acum mi'am adus aminte ca l'am mai scos la o tema si ne'au facut adminii panarama ca scoatem core panels sau ceva de genu,, o mai scoatem ?

**Comment by cristianraiber** [comment]
scoatrm, scoatem

**Comment by cristianraiber** [comment]
@giucu91 - aici am gresit eu, ar trebui lasat panel-ul asta si adaugat un upsell cum ca in versiunea PRO se gasesc si mai multe color controls.
