### ISSUE TITLE
Nav menu - font-size not like in PSD

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/allegiant-lite#13]
PSD: Raleway, 13px
Tu: Raleway, 17.6 Px (1.1 em)

**Comment by cristianraiber** [comment]
@giucu91 - tot n-a fost rezolvat asta

**Comment by giucu91** [comment]
@cristianraiber zi'mi tu cat sa pun ca in psd e 13 px si eu am pus 0.813em.
