### ISSUE TITLE
Blog layout issue

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/allegiant-lite#19]
Tu:

![image](https://cloud.githubusercontent.com/assets/7841556/20390825/376b68b8-acd9-11e6-9944-535b7494d176.png)

---

PSD:

![image](https://cloud.githubusercontent.com/assets/7841556/20390834/403b27b2-acd9-11e6-837b-04e56318ef02.png)

**Comment by cristianraiber** [comment]
@giucu91 

stanga: psd; dreapta: tu

![image](https://cloud.githubusercontent.com/assets/7841556/20535163/79c46b44-b0ec-11e6-809c-7aee515c095b.png)

**Comment by AnaMaican** [comment]
@giucu91 In continuare butonul de read more are alte dimensiuni:
- tu- 190 x 45
-psd- 160 x 43

Font size diferit titlu:
-tu- 25 px
-psd- 20 px

Line height titlu:
-tu- 30 px
-psd- 26 px
