### ISSUE TITLE
Double notifications - get started

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/allegiant-lite#28]
Ar trebui sa apara doar unul din cele doua notificari.

![image](https://cloud.githubusercontent.com/assets/23457094/20554613/cd7483cc-b165-11e6-9a9c-298a694ec284.png)

**Comment by cristianraiber** [comment]
@giucu91 
![image](https://cloud.githubusercontent.com/assets/7841556/20679066/ffb9b6d2-b5a1-11e6-8cd5-763661d390a4.png)

Still not fixed.
