### ISSUE TITLE
Appearance - About Allegiant - Changelog improvement

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/allegiant-lite#35]
Daca poti te rog sa lasi acel spatiu care este in a doua poza intre Version si Getting Started si sa bolduiesti 'Version 1.0.0'.

![image](https://cloud.githubusercontent.com/assets/23457094/20830123/bf258e64-b887-11e6-9ee7-4240c7a736f4.png)

---

![image](https://cloud.githubusercontent.com/assets/23457094/20830145/d5f70618-b887-11e6-939a-ae09bad93627.png)

**Comment by AnaMaican** [comment]
Scoate te rog "-".

![image](https://cloud.githubusercontent.com/assets/23457094/20893847/e7c1179e-bb1b-11e6-8f81-f5937ecc6b5c.png)

**Comment by giucu91** [comment]
We don't have this section anymore
