### ISSUE TITLE
Picture hover blur

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/allegiant-lite#39]
Cand faci hover peste poza mi se pare blur-ul diferit de cel din PSD. 

PSD:
![image](https://cloud.githubusercontent.com/assets/23457094/20840252/45d5e9a6-b8b8-11e6-9703-5b22e52e8e54.png)

Implementare:

![image](https://cloud.githubusercontent.com/assets/23457094/20840279/60775c68-b8b8-11e6-9d98-41562f739191.png)

**Comment by giucu91** [comment]
@cristianraiber can we close this ? This issue is for Ascendant
