### ISSUE TITLE
Service Icon size

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/allegiant-lite#44]
Am senzatia ca iconitele implementate sunt mai mari decat cele din PSD. Puteti masura voi va rog Service Icon-urile? Eu nu ma pricep atat de bine cu Photoshop-ul.

Implementare:

![image](https://cloud.githubusercontent.com/assets/23457094/20885172/016631c6-baf8-11e6-84c6-8e3d9f4b1cc6.png)

PSD:

![image](https://cloud.githubusercontent.com/assets/23457094/20885185/1afa75fc-baf8-11e6-92e1-52375845c146.png)

**Comment by cristianraiber** [comment]
@ngabyn - asteptam final review aici

**Comment by giucu91** [comment]
@cristianraiber @ngabyn cand face'ti review tineti cont ca iconitele din photoshop sunt vectori si nu font. Sunt facute de cristina.

**Comment by giucu91** [comment]
@cristianraiber can we close this ? This issue is for Ascendant
