### ISSUE TITLE
WooCommerce design issue

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/allegiant-lite#49]
![image](https://cloud.githubusercontent.com/assets/7841556/23062675/6308ecb0-f50f-11e6-83b4-2a45a9b19f10.png)

See this ticket for more details: https://secure.helpscout.net/conversation/320457643/4414/?folderId=1090960

**Comment by giucu91** [comment]
@cristianraiber This bug is for Brilliance PRR.
