### ISSUE TITLE
Change footer link

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/allegiant-lite#5]
Link-ul din footer, se va schimba cu asta: 

`<a href="https://www.machothemes.com/" title="Professional WordPress Themes" rel="dofollow">Macho Themes</a>`

**Comment by giucu91** [comment]
@cristianraiber o sa fie doar Macho Themes in footer sau Allegiant by Macho Themes ?

**Comment by cristianraiber** [comment]
a doua varianta

**Comment by cristianraiber** [comment]
@giucu91 - link-ul din footer trebuie sa duca catre https://cpothemes.com/ fara `www.`
