### ISSUE TITLE
Polylang does not work with the theme

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/allegiant-lite#50]
This is the error
![bb7c4fc083717e3fbbd9695de41100e7](https://cloud.githubusercontent.com/assets/26008574/24503101/58334d66-1559-11e7-90e0-ad1bfd546c54.png)

**Comment by pwzawadzki** [comment]
Anybody?

**Comment by cristianraiber** [comment]
@pwzawadzki - this seems to be working fine.
