### ISSUE TITLE
Issue with the Clients section on mobile

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/allegiant-lite#56]
The first two are ok, but the next are smaller.
https://gyazo.com/d92403d55df1f662cde563dda2d5b94c

**Comment by cristianraiber** [comment]
@mplusb - what screen resolution / device?

**Comment by mplusb** [comment]
toate deviceurile care au width pana in 800px

**Comment by mplusb** [comment]
https://github.com/MachoThemes/allegiant-lite/blob/01a6f431071362c7f0b2aa2561f7e150744528bb/core/css/base.css#L679

**Comment by giucu91** [comment]
@cristianraiber I see that on desktop there are 5 item per column, but on mobile they are arranged 2 on each column and 3 on the second. Should we change this ?

**Comment by cristianraiber** [comment]
@ngabyn - need an opinion on this
