### ISSUE TITLE
Mobile menu issues on responsive

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/allegiant-lite#58]
The Mobile Menu on my allegiant theme website isn't working, nothing happens when you press the menu button.
It works fine on the desktop, but on iphone and ipad (portrait) when the menu lines appear it doesn't.

More details, here: https://secure.helpscout.net/conversation/433478995/7640/?folderId=1090954

**Comment by giucu91** [comment]
@cristianraiber the mobile menu is working, also I checked the client's site and it's working.

**Comment by cristianraiber** [comment]
Yep, se pare ca avea un plugin de minificare de fisiere JS care ne crapa tema.
