### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/allegiant-lite#71]
After installing and activating plugins from the "Recommended actions" section, when trying to import the demo it blocks in the below way.
![import bug](https://user-images.githubusercontent.com/44024114/63038309-8b858c80-bec9-11e9-85af-ce90021be403.PNG)

**Comment by razvanaldea89** [comment]
Seems like is just working slower on localhost ( very slow ). Tested on live environment and worked OK.

**Comment by cristianraiber** [comment]
@giucu91 - we should look into why this is taking so long to import. I remember it taking less. A lot less time to import the content.

**Comment by cristianraiber** [comment]
Duplicate of #72
